name: Deploy to GitHub pages
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Install pnpm
        run: npm i -g pnpm
      - run: pnpm install
      - run: pnpm build
      # - uses: cypress-io/github-action@v5
      #   with:
      #     install: false
      #     start: pnpm prod-start
      # - uses: actions/upload-artifact@v3
      #   if: failure()
      #   with:
      #     name: cypress-images
      #     path: cypress/integration/__image_snapshots__/
      # todo link vercel deployment
      - run: pnpx zardoy-release node
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
