name: Deploy to GitHub pages
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Install pnpm
        run: npm i -g vercel pnpm
      # - run: pnpm install
      # - run: pnpm build
      - run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      # will install + build to .vercel/output/static
      - run: vercel build --token=${{ secrets.VERCEL_TOKEN }} --prod
      - run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --prod
      - run: pnpx zardoy-release node
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vercel/output/static
          force_orphan: true
